version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: obligatorio_bd2
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: obligatorio
      MYSQL_DATABASE: penca_db
      MYSQL_USER: penca
      MYSQL_PASSWORD: penca2024
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db:/docker-entrypoint-initdb.d
